services:
  backend:
    image: backend
    build: ./Backend
    ports:
      - "5000:5000"
    networks:
      - DocLabsNetwork
  tests:
    image: tests
    build: ./Tests
    networks:
      - DocLabsNetwork

networks:
  DocLabsNetwork:
    driver: bridge
