services:
  backend:
    image: backend
    build: ./Backend
    container_name: backend
    volumes:
      - ./Backend:/app
    ports:
      - "5000:5000"
    networks:
      - DocLabsNetwork
  tests:
    image: tests
    build: ./Tests
    container_name: tests
    volumes:
      - ./Tests:/app
    networks:
      - DocLabsNetwork

networks:
  DocLabsNetwork:
    driver: bridge
